#!/bin/bash 

check=0
for((i=0;i<8;i++));do
	gov=$(cat /sys/devices/system/cpu/cpu${i}/cpufreq/scaling_governor);
	govn=$(cat /sys/devices/system/cpu/cpu${i+1}/cpufreq/scaling_governor);
	if [ $gov = $govn ];then
		check=1
	fi
done

if [ $check == 1 ];then
	echo $gov
else
	echo "Not Okay!"
fi

